remote_config_sync.sync:
  route_name: remote_config_sync.sync
  title: 'Sync'
  base_route: remote_config_sync.index
  weight: 1

remote_config_sync.local:
  route_name : remote_config_sync.local
  title: 'Local'
  base_route: remote_config_sync.index
  weight: 2

remote_config_sync.remote:
  route_name: remote_config_sync.remote
  title: 'Remote'
  base_route: remote_config_sync.index
  weight: 3

