remote_config_sync.index:
  title: 'Remote config sync'
  description: 'Synchronize configuration between local and remote site.'
  route_name: remote_config_sync.sync
  parent: system.admin_config_development
