remote_config_sync.sync:
  path: '/admin/config/development/remote-config-sync/sync'
  defaults:
    _form: '\Drupal\remote_config_sync\Form\SyncForm'
    _title: 'Sync'
  requirements:
    _permission: 'access remote config sync admin'

remote_config_sync.remotes:
  path: '/admin/config/development/remote-config-sync/remotes'
  defaults:
    _form: '\Drupal\remote_config_sync\Form\RemotesForm'
    _title: 'Remotes'
  requirements:
    _permission: 'access remote config sync admin'

remote_config_sync.settings:
  path: '/admin/config/development/remote-config-sync/settings'
  defaults:
    _controller: '\Drupal\remote_config_sync\Controller\PageController::settings'
    _title: 'Settings'
  requirements:
    _permission: 'access remote config sync admin'

remote_config_sync.api_v1_config:
  path: '/api/v1/remote-config-sync'
  methods: [POST]
  defaults:
    _controller: '\Drupal\remote_config_sync\Controller\SyncController::post'
    _title: 'Post'
  requirements:
    _permission: 'access content'
