remote_config_sync.sync:
  route_name: remote_config_sync.sync
  title: 'Sync'
  base_route: remote_config_sync.index
  weight: 1

remote_config_sync.remotes:
  route_name: remote_config_sync.remotes
  title: 'Remotes'
  base_route: remote_config_sync.index
  weight: 2

remote_config_sync.settings:
  route_name : remote_config_sync.settings
  title: 'Settings'
  base_route: remote_config_sync.index
  weight: 3
